/* eslint-disable no-unused-vars */
export enum ActionType {
  USER_LOGIN = 'USER_LOGIN',
  USER_REGISTER = 'USER_REGISTER',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_DATA = 'USER_DATA',
  RESET_AUTH_REDUCER = 'RESET_AUTH_REDUCER',

  DATA_ORDERS = 'DATA_ORDERS',
  ORDER_CART = 'ORDER_CART',
  RESET_ORDER_CART = 'RESET_ORDER_CART',

  DATA_SERVICE = 'DATA_SERVICE'
}
